services:
  mysql:
    image: mysql:8.0           # 使用官方 MySQL 8.0 镜像
    container_name: mysql-db  # 容器名称，可以根据需要更改
    restart: always           # 确保容器在崩溃后自动重启
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # MySQL root 用户密码
      MYSQL_DATABASE: my_database         # 初始化的数据库名称（可选）
      MYSQL_USER: my_user                 # 初始化的用户名（可选）
      MYSQL_PASSWORD: my_password         # 初始化的用户密码（可选）
    ports:
      - "3306:3306"                        # 将容器的 3306 端口映射到主机的 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化

volumes:
  mysql_data: